# Generated by Django 2.2.8 on 2020-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200521_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='S'),
            preserve_default=False,
        ),
    ]
